INHERIT: ./common/mkdocs_base.yml

site_dir: site
site_name: Federated Learning
# site_description: sasano8's portfolio
# site_url: https://sasano8.github.io/fedml_sample/
repo_name: Federated Learning
repo_url: https://github.com/sasano8/fedml_sample
edit_uri: edit/main/docs/

nav:
  - はじめに: "index.md"
  - 調査: "research.md"
  - インストレーション: "installation.md"
  - 用語集: "glossary.md"
  - api: "openapi/api.html"
  - コードリーディング: "code_reading.md"
  - 技術選定: "tech_selection.md"
