- hosts: nfs
  tasks:
    - name: test login to nfs
      command: echo hello nfs

- hosts: head
  tasks:
    - name: test login to head
      command: echo hello head

- hosts: nodes
  tasks:
    - name: Fetch the file from the mwiapp01 to master
      copy: src=../scripts dest=. mode=+x
