- hosts: nfs
  tasks:
    - name: test login to nfs
      command: echo hello nfs

- hosts: ~(head|nodes|standalone)
  tasks:
    - name: Fetch the file from the mwiapp01 to master
      copy: src=../scripts dest=. mode=+x
    - name: create log directory
      shell: mkdir -p logs
